### ISSUE TITLE
给你增加

### ISSUE THREAD

**Issue by loongzcode** [Snuffel233/halo-theme-crux#1]
希望能够适配相册和友链插件

**Comment by Snuffel233** [comment]
收到，将会在本周晚些时候的版本中加入该feature

**Comment by loongzcode** [comment]
> 收到，将会在本周晚些时候的版本中加入该feature

好的谢谢

**Comment by Snuffel233** [comment]
功能已实现
![192.168.2.7_8090_photosiPad-Air64ce6da0ab89291d.png](https://img.picgo.net/2023/07/08/192.168.2.7_8090_photosiPad-Air64ce6da0ab89291d.png)
![192.168.2.7_8090_linksiPad-Air3f308c475cdd0296.png](https://img.picgo.net/2023/07/08/192.168.2.7_8090_linksiPad-Air3f308c475cdd0296.png)
