### ISSUE TITLE
文章问题

### ISSUE THREAD

**Issue by loongzcode** [Snuffel233/halo-theme-crux#7]
希望增加文章目录，当我就想看文章的哪一点的时候，要翻好久。还有文章置顶好像也没有特定的样式

**Comment by Snuffel233** [comment]
文章顶置已修复![alkaid.ink_iPad-Air-10030fcc3590faa82.png](https://img.picgo.net/2023/07/08/alkaid.ink_iPad-Air-10030fcc3590faa82.png)
目录会在接下来的版本加入

**Comment by Snuffel233** [comment]
全部内容已修复
- 置顶文章：823b545c4a4ae344b56993c902578c1042660f55
- 文章目录：4ec2ebaea844ab987c79ba0e0185c96690ead5a0
